[tool.poetry]
name = "pycape"
version = "0.3.0"
description = "A set of Python modules for interacting with your Cape Privacy data."
authors = ["Cape Privacy <contact@capeprivacy.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://capeprivacy.com/"
repository = "https://github.com/capeprivacy/pycape"
documentation = "https://docs.capeprivacy.com/libraries/pycape"

[tool.poetry.dependencies]
python = "^3.6.1"
requests = "~2.25.0"
responses = "~0.10.15"
marshmallow = ">=3.9.1,<3.12.0"
pandas = "~1.1.5"
tabulate = "0.8.9"
boto3 = ">=1.16,<1.18"

[tool.poetry.dev-dependencies]
pytest = "~6.2.0"
coverage = "5.3"
black = "~19.10b0"
pytest-cov = "~2.10.0"
pytest-mock = "~3.5.1"
pytest-httpserver = "~0.3.4"
flake8 = "~3.8.3"
flake8-black = "~0.2.0"
isort = "~5.1.4"
mkdocs-material = "5.5.3"
mkdocstrings = "0.15.0"
pydoc-markdown = "3.2.0"

[tool.isort]
line_length = 120
force_single_line = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
